package de.polo.voidroleplay.utils;

import com.google.gson.Gson;
import net.kyori.adventure.inventory.Book;
import net.kyori.adventure.text.Component;
import net.kyori.adventure.text.serializer.json.JSONComponentSerializer;
import org.bukkit.Material;
import org.bukkit.inventory.ItemStack;
import org.bukkit.inventory.meta.BookMeta;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import java.util.List;

/**
 * A utility class for serializing and deserializing Minecraft book data
 * using the Adventure API and Google's Gson library. This class handles
 * the conversion of book metadata and pages between Java objects and JSON format.
 * <p>
 * Usage Example:
 * <blockquote><pre>
 * BookMeta meta = // Obtain a BookMeta instance from Bukkit API
 * BookSerializer serializer = new BookSerializer(meta);
 * String json = serializer.serializeAll(); // Serialize book to JSON
 * Book book = serializer.deserializeAll(json); // Deserialize JSON to book
 * </pre></blockquote>
 * </p>
 *
 * @author Erik Pförtner
 */
public class BookSerializer {
    /**
     * The default page separator used in serialization.
     */
    public static final String PAGE_SEPARATOR = ";";

    /**
     * The {@link BookMeta} instance representing the book metadata to be serialized or deserialized.
     */
    private final BookMeta meta;
    /**
     * The modified page separator used in serialization, if set.
     */
    @Nullable
    private final String modifiedPageSeparator;
    /**
     * The {@link JSONComponentSerializer} used for serializing and deserializing {@link Component} instances.
     */
    private static final JSONComponentSerializer serializer = JSONComponentSerializer.json();

    /**
     * Constructs a new {@code BookSerializer} with the specified {@link BookMeta}.
     *
     * @param meta The book metadata to serialize or deserialize. Must not be {@code null}.
     * @throws NullPointerException if {@code meta} is {@code null}.
     */
    public BookSerializer(@NotNull final BookMeta meta) {
        this.meta = meta;
        this.modifiedPageSeparator = null;
    }

    /**
     * Constructs a new {@code BookSerializer} with the specified {@link BookMeta} and modified page separator.
     *
     * @param meta                  The book metadata to serialize or deserialize. Must not be {@code null}.
     * @param modifiedPageSeparator The modified page separator. Must not be {@code null}.
     * @throws NullPointerException if {@code meta} is {@code null}.
     */
    public BookSerializer(@NotNull final BookMeta meta, @NotNull final String modifiedPageSeparator) {
        this.meta = meta;
        this.modifiedPageSeparator = modifiedPageSeparator;
    }

    /**
     * Returns the associated {@link BookMeta} instance.
     *
     * @return The {@link BookMeta} instance. Never {@code null}.
     */
    @NotNull
    public BookMeta getMeta() {
        return meta;
    }

    /**
     * Returns the {@link JSONComponentSerializer} used for serialization.
     *
     * @return The {@link JSONComponentSerializer}. Never {@code null}.
     */
    @NotNull
    public JSONComponentSerializer getSerializer() {
        return serializer;
    }

    /**
     * Returns the modified page separator used in serialization, if set.
     *
     * @return The modified page separator, or {@code null} if not set.
     */
    @Nullable
    public String getModifiedPageSeparator() {
        return modifiedPageSeparator;
    }

    /**
     * Serializes the book metadata and pages into a JSON string.
     * The output JSON contains the book's title, author, and content.
     * If the title or author is missing, default values are used.
     *
     * @return The serialized JSON string. Never {@code null}.
     */
    @NotNull
    public String serializeAll() {
        Gson gson = new Gson();
        String title = serializer.serialize(meta.title() == null ? Component.text("Unknown Title") : meta.title());
        String author = serializer.serialize(meta.author() == null ? Component.text("Unknown Author") : meta.author());
        List<Component> pages = meta.pages();
        StringBuilder contentBuilder = new StringBuilder();
        for (Component page : pages) {
            contentBuilder.append(serializer.serialize(page)).append(PAGE_SEPARATOR);
        }

        return gson.toJson(new BookData(title, author, contentBuilder.toString()));
    }

    /**
     * Deserializes a JSON string back into a {@link Book} instance.
     * The JSON must conform to the structure generated by {@link #serializeAll()}.
     *
     * @param json The JSON string to deserialize. Must not be {@code null}.
     * @return The deserialized {@link Book} instance. Never {@code null}.
     * @throws com.google.gson.JsonSyntaxException If the JSON is malformed or does not match the expected structure.
     */
    @NotNull
    public static Book deserializeAll(String json) {
        Gson gson = new Gson();
        BookData data = gson.fromJson(json, BookData.class);

        List<String> pages = List.of(data.content().split(PAGE_SEPARATOR));
        List<Component> components = List.of(pages.stream().map(serializer::deserialize).toArray(Component[]::new));

        return Book.book(
                serializer.deserialize(data.title()),
                serializer.deserialize(data.author()),
                components
        );
    }

    /**
     * Deserializes a JSON string back into a {@link ItemStack} instance.
     * The JSON must conform to the structure generated by {@link #serializeAll()}.
     *
     * @param json The JSON string to deserialize. Must not be {@code null}.
     * @return The deserialized {@link ItemStack} instance. Never {@code null}.
     * @throws com.google.gson.JsonSyntaxException If the JSON is malformed or does not match the expected structure.
     */
    @NotNull
    public static ItemStack deserializeItemStack(String json) {
        Gson gson = new Gson();
        BookData data = gson.fromJson(json, BookData.class);

        List<String> pages = List.of(data.content().split(PAGE_SEPARATOR));
        List<Component> components = List.of(pages.stream().map(serializer::deserialize).toArray(Component[]::new));

        ItemStack item = new ItemStack(Material.WRITTEN_BOOK);
        BookMeta meta = (BookMeta) item.getItemMeta();
        meta.title(serializer.deserialize(data.title()));
        meta.author(serializer.deserialize(data.author()));
        meta.pages(components);

        item.setItemMeta(meta);
        return item;
    }

    /**
     * Retrieves the page separator string used in serialization.
     * If a modified page separator is set, it is returned;
     * otherwise, the default page separator is returned.
     *
     * @return The page separator string, either the modified value or the default value. Never null.
     */
    @NotNull
    private String getPageSeparator() {
        return modifiedPageSeparator != null ? modifiedPageSeparator : PAGE_SEPARATOR;
    }

    /**
     * A record representing the serialized data of a book, including its title, author, and content.
     */
    private record BookData(String title, String author, String content) {
    }
}
