name: VoidRoleplay
version: '${project.version}'
main: de.polo.voidroleplay.Main
api-version: 1.16
authors: [ Polo66 ]
description: VoidRoleplay Script
depend: [Votifier, dynmap]

commands:
  aduty:
    aliases: ad
  setgroup:
  geldbeutel:
    aliases: gb
  personalausweis:
    aliases: perso
  teamchat:
    aliases: tc
  leadfrak:
  fraktionschat:
    aliases: f
  uninvite:
  setloc:
  setfraktion:
    aliases: setfrak
  adminuninvite:
    aliases: auninvite
  guidechat:
    aliases: gc
  support:
    aliases: [report, help]
  cancelsupport:
  acceptsupport:
    aliases: asupport
  closesupport:
    aliases: csupport
  target-ip:
    aliases: tip
  tpto:
  adminrevive:
    aliases: arevive
  registeratm:
  playerinfo:
    aliases: pi
  me:
    aliases: minecraft:me
  announce:
    aliases: ac
  gov:
  tickets:
  team:
  shop:
  invite:
  annehmen:
  ablehnen:
  rent:
  holzfäller:
  apfelsammler:
  minenarbeiter:
  arrest:
  tp:
  tphere:
  speed:
  bossmenu:
  kick:
  ooc:
  plugins:
    aliases: pl
  vote:
  setrankname:
  setrankpayday:
  cp:
    aliases: controlpanel
  sms:
  call:
  auflegen:
    aliases: endcall
  jailtime:
  drop:
  lebensmittellieferant:
  ban:
  unban:
  car:
    aliases: [vehicle, auto]
  getveh:
    aliases: getvehicle
  gotoveh:
    aliases: gotovehicle
  navi:
    aliases: [navigation, nav, route, gps]
  einreise:
  registerhouse:
  reinforcement:
    aliases: [reinf, r]
  buyhouse:
  mieters:
  unrent:
  frisk:
    aliases: [search, durchsuchen]
  blacklist:
    aliases: bl
  ffa:
  npc:
  redeem:
  whistle:
    aliases: [w, flüstern]
  shout:
    aliases: [s, schreien]
  prteamchat:
    aliases: pr
  eventteamchat:
    aliases: et
  bauteamchat:
    aliases: bt
  setsecondaryteam:
  stats:
    aliases: money
  revive:
  service:
  acceptservice:
  services:
  cancelservice:
  closeservice:
  tslink:
  tsunlink:
  orten:
  gangwar:
  youtube:
  discord:
  departmentchat:
    aliases: d
  member:
  farmer:
  postbote:
  müllmann:
  contracts:
    aliases: kopfgelder
  contract:
    aliases: kopfgeld
  nachrichten:
  businesschat:
    aliases: bc
  leadbusiness:
  fraktionsinfo:
    aliases: [finfo, frakinfo]
  beziehung:
  trennen:
  antrag:
  self:
  garage:
  akten:
  spec:
    aliases: spectator
  msg:
  leaderchat:
    aliases: [lchat, lc]
  frakstats:
    aliases: [fstats, fraktionsstats]
  checkinv:
  bizinvite:
    aliases: businessinvite
  shoprob:
  respawn:
  dealer:
  farming:
  gethead:
  factions:
    aliases: fraktionen
  serverreload:
  serverstop:
  giverank:
  forum:
  autoban:
    aliases: aban
  banlist:
  gm:
  note:
  streetwar:
  getskin:
  registerblock:
  labor:
  apotheke:
  apotheken:
  plant:
  plants:
    aliases: plantagen
  business:
  equip:
  fdoor:
  changespawn:
  findlaboratory:
    aliases: findlabor
  tell:
  invsee:
  use:
  ausziehen:
  company:
  dailybonus:
  winzer:
  rebstock:
  muschelsammler:
  gasstation:
    aliases: tankstelle
  resetbonusentry:
  duty:
    aliases: dienst
  deletebrokenentities:
  admingiverank:
    aliases: agiverank
  subgroup:
  subgroupchat:
    aliases: sc
  permban:
  fly:
  workstation:
  waffenhersteller:
  sperrzone:
  sperrzonen:
  faq:
  karma:
  seasonpass:
  forcedrop:
  beginnerpass:
    aliases: neulingspass
  blacklists:
  houseban:
    aliases: hausverbot
  jail:
  ticket:
  akte:
  gottesdienst:
  event:
  jesuskreuz:
  marry:
  kirchensteuer:
  segen:
  taufe:
  würfeln:
  alliance:
    aliases: bündnis
  openinv:
  geworben:
  kicksecondaryteam:
  auktion:
  fixblock:
  pfeifentransport:
  test:
  blacklistreasons:
  modifyblacklist:
    aliases: mbl
  autoblacklist:
    aliases: [abl, ablacklist]
  afk:
  secondaryteaminfo:
    aliases: stinfo
  vertrag:
  settings:
  subteam:
  subteamchat:
    aliases: [stc]
  setmotd:
  voteshop:
  anwalt:
  houseaddon:
  sprenggürtel:
  bombe:
  cook:
  registerfactionbanner:
  sperrinfo:
  rbreset: