name: MetropiaCity
version: '${project.version}'
main: de.polo.metropiacity.Main
api-version: 1.16
authors: [ Polo66 ]
description: MetropiaCity Roleplay
depend: [Votifier]

commands:
  aduty:
    aliases: ad
  setgroup:
  geldbeutel:
    aliases: gb
  personalausweis:
    aliases: perso
  teamchat:
    aliases: tc
  leadfrak:
  fraktionschat:
    aliases: f
  uninvite:
  setloc:
  setfraktion:
    aliases: setfrak
  adminuninvite:
    aliases: auninvite
  guidechat:
    aliases: gc
  support:
    aliases: [report, help]
  cancelsupport:
  acceptsupport:
    aliases: asupport
  closesupport:
    aliases: csupport
  target-ip:
    aliases: tip
  tpto:
  adminrevive:
    aliases: arevive
  registeratm:
  playerinfo:
    aliases: pi
  me:
  announce:
    aliases: ac
  gov:
  tickets:
  team:
  shop:
  invite:
  annehmen:
  ablehnen:
  rent:
  holzfäller:
  apfelsammler:
  minenarbeiter:
  arrest:
  tp:
  tphere:
  speed:
  bossmenu:
  kick:
  ooc:
  plugins:
    aliases: pl
  adminmenu:
    aliases: amenu
  vote:
  setrankname:
  setrankpayday:
  cp:
    aliases: controlpanel
  sms:
  call:
  auflegen:
    aliases: endcall
  jailtime:
  drop:
  lebensmittellieferant:
  ban:
  unban:
  setblockvalue:
  car:
    aliases: [vehicle, auto]
  getveh:
    aliases: getvehicle
  gotoveh:
    aliases: gotovehicle
  navi:
    aliases: [navigation, nav, route, gps]
  einreise:
  registerhouse:
  reinforcement:
    aliases: [reinf, r]
  buyhouse:
  mieters:
  unrent:
  frisk:
    aliases: [search, durchsuchen]
  blacklist:
    aliases: bl
  ffa:
  npc:
  redeem:
  link:
    aliases: forum
  whistle:
    aliases: [w, flüstern]
  shout:
    aliases: [s, schreien]
  prteamchat:
    aliases: pr
  eventteamchat:
    aliases: et
  bauteamchat:
    aliases: bt
  setsecondaryteam:
  stats:
  revive:
  service:
  acceptservice:
  services:
  cancelservice:
  closeservice:
  tslink:
  verify:
  tsunlink:
  orten:
  gangwar:
  youtube:
  discord:
  departmentchat:
    aliases: d
  member:
  farmer:
  postbote:
  müllmann:
  contracts:
    aliases: kopfgelder
  contract:
    aliases: kopfgeld
  nachrichten:
  businesschat:
    aliases: bc
  leadbusiness:
  fraktionsinfo:
    aliases: [finfo, frakinfo]
  beziehung:
  trennen:
  antrag:
  self:
  garage:
  akten:
  spec:
    aliases: spectator
  msg:
  leaderchat:
    aliases: [lchat, lc]
  frakstats:
    aliases: [fstats, fraktionsstats]
  checkinv:
  bizinvite:
    aliases: businessinvite
  shoprob:
  respawn:
  dealer:
  farming:
  gethead:
  factions:
    aliases: fraktionen
  serverreload:
  serverstop: